version: '3.8'

services:
  next-boilerplate:
    container_name: next-boilerplate
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: always # Automatyczny restart w razie awarii
