version: '3.8'

services:
  next-boilerplate:
    container_name: next-boilerplate
    build:
      context: .
      dockerfile: Dockerfile.prod # Wymuszenie użycia Dockerfile.prod
    ports:
      - '3000:3000'
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  node_modules:
  build: