version: '3.8'

services:
  next-boilerplate:
    container_name: next-boilerplate
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    restart: always
    environment:
      - APP_PORT=3000
    command: ['npm', 'run', 'start:prod'] # Wymuszenie trybu produkcyjnego
