version: '3.8'

services:
  next-boilerplate:
    container_name: next-boilerplate
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    env_file:
      - .env
    restart: always
