version: '3.8'

services:
  next-boilerplate:
    container_name: next-boilerplate
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env.example
    restart: always