version: '3.8'

services:
  next-boilerplate:
    container_name: next-boilerplate
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '${APP_PORT}:${APP_PORT}'
    restart: always
    environment:
      - APP_PORT=${APP_PORT}
      - NODE_ENV=production
    command: ['sh', '-c', 'npm run start:prod']
