version: '3.8'
services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: sebastiankociuba/next-boilerplate:latest
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
