name: Test and Deploy Next.js

on:
  push:
    branches:
      - deploy # Deploy to EC2 only after push to `deploy`

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prettier-check:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Run prettier check
        run: pnpm prettier:check

  eslint-check:
    name: Eslint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Run eslint check
        run: pnpm eslint:format

  jest-check:
    name: Tests - jest
    needs: [prettier-check, eslint-check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test:ci
        env:
          CI: true

  nextjs-build:
    name: Build Docker Image
    needs: [jest-check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker buildx build --push --tag your-dockerhub-username/next-boilerplate:latest -f Dockerfile.prod .

  deploy:
    name: Deploy to EC2
    needs: [nextjs-build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Container on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull your-dockerhub-username/next-boilerplate:latest
            sudo docker stop next-boilerplate || true
            sudo docker rm next-boilerplate || true
            sudo docker run -d --name next-boilerplate -p 3000:3000 --env-file .env your-dockerhub-username/next-boilerplate:latest
