name: Test and Deploy Next.js

on:
  push:
    branches:
      - deploy # Deploy to EC2 only after push to `deploy`

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prettier-check:
    name: Prettier check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Run prettier check
        run: pnpm prettier:check

  eslint-check:
    name: Eslint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Run eslint check
        run: pnpm eslint:format

  jest-check:
    name: Tests - jest
    needs: [prettier-check, eslint-check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test:ci
        env:
          CI: true

  build:
    name: Build Docker Image
    needs: [jest-check]
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: sebastiankociuba/next-boilerplate:latest

  deploy:
    name: Deploy to EC2
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Container on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Start deployment on EC2..."

            # Usuń stare wersje Dockera i zainstaluj na nowo
            echo "Aktualizacja pakietów i instalacja Dockera..."
            sudo apt remove -y docker docker.io containerd containerd.io || true
            sudo apt update -y
            sudo apt install -y docker.io

            # Ustaw uprawnienia dla Dockera
            echo "Dodanie użytkownika ubuntu do grupy docker..."
            sudo usermod -aG docker ubuntu
            newgrp docker  # Odświeżenie grupy, by uniknąć potrzeby wylogowania

            # Pobierz najnowszy obraz Dockera
            echo "Pobieranie najnowszego obrazu aplikacji..."
            docker pull sebastiankociuba/next-boilerplate:latest

            # Zatrzymaj i usuń poprzedni kontener
            echo "Zatrzymywanie starego kontenera (jeśli istnieje)..."
            docker stop next-boilerplate || true
            docker rm next-boilerplate || true

            # Sprawdź, czy plik .env istnieje
            if [ ! -f "/home/ubuntu/.env" ]; then
              echo "Plik .env nie istnieje! Kontener uruchomi się bez niego."
              ENV_OPTION=""
            else
              ENV_OPTION="--env-file /home/ubuntu/.env"
            fi

            # Uruchom kontener w tle na porcie 3000
            echo "Uruchamianie nowego kontenera..."
            docker run -d \
              --name next-boilerplate \
              -p 3000:3000 \
              --restart unless-stopped \
              $ENV_OPTION \
              sebastiankociuba/next-boilerplate:latest

            echo "Deployment zakończony sukcesem!"
